#! /user/bin/python3

sequence_of_interest = open('exons_remote.fasta').read().split()[1]

window=30
offset=0
counter=0

segment_start = list(range(0,len(seqeunce_of_interest),3))

segments= []


for seq_bits in sequence_of_interest :
 tempseq= sequence_of_interest[seq_bits : seq_bits:window].upper()
 segments= segments + [tempseq]
 tempGC = int(100* (tempseq.count('G') + tempseq.count('C'))/len(tempseq))
 
window=33
offset=3
counter += 1


